In [16]:
#  pip install numpy
import numpy as np

print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

np.zeros([5, 7, 8, ])

np.zeros((5, 7, 8, ))

np.ones((3,5))

np.eye(7)

np.arange(12)

np.arange(4,20) # [4, 20[

np.arange(-12, 1)

arreglo_pares = np.arange(0, 20, 2)
print(arreglo_pares.size)
print(len(arreglo_pares))
arreglo_tres_dimensiones = np.zeros((2,3,4))
print(arreglo_tres_dimensiones.shape)

arreglo_pares.reshape(5,2)

arreglo_pares.reshape(2,5)

np.arange(24).reshape(6,4).reshape(8,3)

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
10
10
(2, 3, 4)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [2]:
print(type(np.array((1,2,3))))

<class 'numpy.ndarray'>


In [3]:
arreglo_pares = np.arange(0, 20, 2)

In [4]:
arreglo_pares.shape

(10,)

In [7]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [8]:
# suma
a + b

array([15, 15, 15])

In [9]:
# resta
a - b

array([5, 5, 5])

In [10]:
# multiplicacion
a * b

array([50, 50, 50])

In [11]:
# division
a / b

array([2., 2., 2.])

In [12]:
# mod
a % b

array([0, 0, 0], dtype=int32)

In [15]:
# Multiplicarr
print(a * 10)

# Sumar
print(a + 7)

# Restar
print(a - 2)

# Dividir
print(a / 2)

# Mod
print(a % 3)

[100 100 100]
[17 17 17]
[8 8 8]
[5. 5. 5.]
[1 1 1]


In [18]:
arreglo_muestra = np.arange(20).reshape(5,2,2)

resp = arreglo_muestra > 5 

resp

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
arreglo_muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [20]:
arreglo_muestra[resp]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
arreglo_muestra[(arreglo_muestra > 5) * (arreglo_muestra < 12) * (arreglo_muestra % 2 == 0)]

array([ 6,  8, 10])

In [25]:
resp_mayor_cinco = arreglo_muestra > 5
arreglo_muestra[resp_mayor_cinco]

resp_menor_doce = arreglo_muestra < 12
arreglo_muestra[resp_menor_doce]

arreglo_muestra[resp_mayor_cinco & resp_menor_doce]
# arreglo_muestra[resp_mayor_cinco | resp_menor_doce]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
resp = (arreglo_muestra > 5) & (arreglo_muestra < 12)
arreglo_muestra[resp]

array([ 6,  7,  8,  9, 10, 11])

In [28]:
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [29]:
B = np.arange(4,8).reshape((2,2))
B

array([[4, 5],
       [6, 7]])

In [30]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [31]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [32]:
B.dot(A)

array([[10, 19],
       [14, 27]])

In [33]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
arreglo_doce.sum()

66

In [35]:
arreglo_doce.min()

0

In [36]:
arreglo_doce.max()

11

In [37]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [38]:
arreglo_doce.reshape(3,2,2).sum(axis=0)

array([[12, 15],
       [18, 21]])

In [39]:
arreglo_doce.reshape(3,2,2).sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [40]:
arreglo_doce.reshape(3,2,2).sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])